---
# Disable line length check (MD013)
MD013: false

# Allow inline HTML
MD033: false

# Allow emphasis with underscore
MD036: false

# Allow blank lines inside blockquotes
MD028: false

# Allow heading level increments greater than 1
MD001: false

# Allow table column count
MD056: false
