# Pre-commit hooks for Jekyll site quality
repos:
  - repo: local
    hooks:
      - id: check-links
        name: Check internal links
        entry: python3 check_links.py
        language: system
        pass_filenames: false
        stages: [commit]
        
      - id: jekyll-build
        name: Jekyll build test
        entry: bundle exec jekyll build --trace
        language: system
        pass_filenames: false
        stages: [commit]