title: Anne Schuth
email: anne.schuth@gmail.com
description: >- #
  Anne Schuth has a PhD in Search and works on AI and Engineering for the Dutch Government
domain: anneschuth.github.io
baseurl: /
url: https://anneschuth.nl
github_username: anneschuth
linkedin_username: anneschuth
bluesky_username: anneschuth.nl
mastodon:
- username: anneschuth
  instance: mastodon.social

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-spaceship

# Custom navigation links
header_pages:
  - about.markdown
  - publications.markdown
  - talks.markdown
  - activities.markdown
  - software.markdown
  - teaching.markdown
  - thesis.markdown
  - press.markdown

paginate: 5

future: true

minima:
  date_format: "%b %-d, %Y"
  social_links:
    github: anneschuth
    linkedin: anneschuth

collections:
  publications:
    output: true
    permalink: /:collection/:name
  talks:
    output: true
    permalink: /:collection/:name
  press:
    output: true
    permalink: /:collection/:name
