title: Anne Schuth
email: anne.schuth@gmail.com
description: >- # 
  Anne Schuth has a PhD in Search, is Head of Engineering, and works on AI for the Dutch Government
domain: anneschuth.github.io
baseurl: /
url: https://anneschuth.nl
twitter_username: anneschuth
github_username: anneschuth
linkedin_username: anneschuth
mastodon:
- username: anneschuth
  instance: mastodon.social

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

paginate: 3

minima:
  date_format: "%b %-d, %Y"
  social_links:
    twitter: anneschuth
    github: anneschuth
    linkedin: anneschuth

collections:
  publications:
    output: true
    permalink: /:collection/:name
